name: Generate Snake Game

# This workflow is triggered automatically at midnight
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the Snake Game from your contributions
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: StefRuseva88
          outputs: dist/snake.svg

      # Push the Snake Animation to the output folder
      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
